import Link from 'next/link';
import PublicHeader from '../../../components/PublicHeader';
import {salesHref,salesContact} from '../../../lib/sourcing-config.mjs';
import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
// Copy is limited to the existing demonstrated request workflow. Company,
// warranty, delivery, address and legal claims need owner-approved wording.
const pages:Record<string,{title:string;paragraphs:string[]}>={
 'about':{title:'About the parts request service',paragraphs:['China Parts Shop presents a requirement-led sourcing workflow for automotive and heavy equipment spare parts. Start with the part description, part number or equipment details so the sourcing team can review the requirement.','The request workflow is capture, identification, sourcing review, quotation discussion and agreed fulfilment. Availability, fitment and commercial terms require confirmation for the specific part. Confirm the specific requirement with the sourcing team.']},
 'how-it-works':{title:'How a parts request works',paragraphs:['Describe the part and quantity, your destination country and an email address or telephone number. Add equipment details or a manufacturer reference if available.','Review the actual request before submitting. Where attachments are enabled, supply a clear photograph or PDF. Keep the reference returned after your enquiry is received.','The team reviews identification and sourcing details. Price, shipping, tax, payment and fulfilment commitments must be agreed before an order is confirmed. Commercial terms are agreed with the team.']},
 'contact':{title:'Contact and request updates',paragraphs:['Use the parts request form for a new requirement. Keep your reference when discussing a request with the team.','Use WhatsApp Sales for a human sales conversation. For part identification, choose technical assistance in the main enquiry. Links open WhatsApp without sending a message automatically.']},
 'faqs':{title:'Frequently asked questions',paragraphs:['What information helps? A part description or OEM reference, quantity, destination country and a way to contact you. Brand, model, VIN or equipment nameplate details can help the review.','Can I request more than one part? Describe your list in the same enquiry. Where uploads are enabled, add readable photos or a PDF. Agree the format with the sourcing team before sending a large spreadsheet.','Does a catalogue listing prove compatibility or stock? No. Confirm the exact application, availability, quality documentation and terms with the sourcing team.','Can I pay or track an order here? Approved company accounts can access the customer portal when activated. Online ordering and payment are not currently offered.']},
 'shipping':{title:'Shipping and fulfilment review',paragraphs:['Include the destination country with the request. Shipping cost, timing, carrier, customs responsibilities and delivery terms are confirmed for each accepted commercial arrangement.','Ask the team for the shipping terms applicable to your requirement.']},
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;return {title:`${pages[slug]?.title??'Information'} | China Parts Shop`};}
export default async function Information({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug];if(!page)notFound();return <><PublicHeader/><main className="request-page"><article className="request-shell"><Link href="/">China Parts Shop</Link><h1>{page.title}</h1>{page.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{slug==='contact'&&<div className="request-actions"><a href={salesHref()} target="_blank" rel="noopener noreferrer">WhatsApp Sales · {salesContact.display}</a><a href="/request?purpose=technical">Talk to a Technical Expert</a></div>}<nav className="request-actions" aria-label="Information pages">{Object.keys(pages).map(key=><Link href={`/information/${key}`} key={key}>{pages[key].title}</Link>)}</nav><p><Link href="/policies">Privacy and service policy preparation</Link></p><Link href="/request">Send Your Enquiry</Link></article></main></>;}
