import Link from 'next/link';
import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
// Copy is limited to the existing demonstrated request workflow. Company,
// warranty, delivery, address and legal claims need owner-approved wording.
const pages:Record<string,{title:string;paragraphs:string[]}>={
 'about':{title:'About the parts request service',paragraphs:['China Parts Shop presents a requirement-led sourcing workflow for automotive and heavy equipment spare parts. Start with the part description, part number or equipment details so the sourcing team can review the requirement.','The request workflow is capture, identification, sourcing review, quotation discussion and agreed fulfilment. Availability, fitment and commercial terms require confirmation for the specific part. Company history, legal entity and service guarantees await owner-approved content.']},
 'how-it-works':{title:'How a parts request works',paragraphs:['Describe the part and quantity, your destination country and an email address or telephone number. Add equipment details or a manufacturer reference if available.','Review the actual request before submitting. Where attachments are enabled, supply a clear photograph or PDF. Keep the returned reference after persistence acknowledges the request.','The team reviews identification and sourcing details. Price, shipping, tax, payment and fulfilment commitments must be agreed before an order is confirmed. Online payment and commercial issuance are not activated in this preparation environment.']},
 'contact':{title:'Contact and request updates',paragraphs:['Use the parts request form for a new requirement. Keep your reference when discussing a request with the team.','The demonstration uses the email and WhatsApp destinations shown below. The owner must confirm the approved contact details before launch. Click-through links open your email or WhatsApp app; they do not send a message automatically.']},
 'faqs':{title:'Frequently asked questions',paragraphs:['What information helps? A part description or OEM reference, quantity, destination country and a way to contact you. Brand, model, VIN or equipment nameplate details can help the review.','Can I request more than one part? The local customer workspace supports multiple lines. The public request form accepts a requirement description and bounded photos/PDFs; spreadsheet parsing and an agreed bulk-list format remain separate work.','Does a catalogue listing prove compatibility or stock? No. Confirm the exact application, availability, quality documentation and terms with the sourcing team.','Can I pay or track an order here? Local preview views demonstrate these workflows with synthetic records. Live customer authentication, payment processing and fulfilment updates require provider setup and approved business rules.']},
 'shipping':{title:'Shipping and fulfilment review',paragraphs:['Include the destination country with the request. Shipping cost, timing, carrier, customs responsibilities and delivery terms are confirmed for each accepted commercial arrangement.','The local customer preview displays a manual tracking timeline. It does not represent a booked shipment or a carrier integration. Published shipping policy requires owner-approved wording.']},
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;return {title:`${pages[slug]?.title??'Information'} | China Parts Shop`};}
export default async function Information({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug];if(!page)notFound();return <main className="request-page"><article className="request-shell"><Link href="/">China Parts Shop</Link><h1>{page.title}</h1>{page.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{slug==='contact'&&<div className="request-actions"><a href="mailto:parts@chinapartsshop.com">Email</a><a href="https://wa.me/447520688566" target="_blank" rel="noopener noreferrer">WhatsApp</a></div>}<nav className="request-actions" aria-label="Information pages">{Object.keys(pages).map(key=><Link href={`/information/${key}`} key={key}>{pages[key].title}</Link>)}</nav><p><Link href="/policies">Privacy and service policy preparation</Link></p><Link href="/request">Prepare a parts request</Link></article></main>;}
