import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {initialPreviewState,applyPreviewCommand,previewSnapshot,PreviewError} from '../lib/preview-domain.mjs';
import {documentPolicy} from '../lib/document-policy.mjs';
import {catalogueFilters} from '../lib/catalogue-reader.mjs';
import {validateWorkspaceCommand} from '../lib/workspace-writer.mjs';
const operation=(type,input)=>({key:randomUUID(),type,input});
const save=(state,actor,type,input)=>applyPreviewCommand(state,actor,operation(type,input)).state;
const denied=(fn,status)=>assert.throws(fn,error=>error.status===status);
test('administration rejects actor spoofing, agent/customer changes, self-demotion and stale memberships',()=>{
 let state=initialPreviewState();
 for(const actor of ['north-agent','customer-a'])denied(()=>save(state,actor,'office.save',{name:'New',active:false}),403);
 denied(()=>save(state,'admin','staff.save',{userId:'admin',version:0,role:'agent',officeId:'north',active:true}),409);
 state=save(state,'admin','staff.save',{userId:'north-agent',version:0,role:'agent',officeId:'south',active:true,label:'Moved demo agent'});
 assert.deepEqual(previewSnapshot(state,'north-agent').requests.map(x=>x.id),['request-b']);
 denied(()=>save(state,'admin','staff.save',{userId:'north-agent',version:0,role:'agent',officeId:'north',active:true}),409);
 state=save(state,'admin','staff.save',{userId:'north-agent',version:1,role:'agent',officeId:'south',active:false});
 assert.throws(()=>previewSnapshot(state,'north-agent'),error=>error instanceof PreviewError&&error.status===403);
 assert.equal(previewSnapshot(state,'customer-a').administration,undefined);
 denied(()=>save(state,'admin','staff.save',{userId:'forged-account',version:null,role:'admin',active:true}),400);
});
test('company reassignment revokes old company access and assignments never grant access',()=>{
 let state=initialPreviewState();
 denied(()=>save(state,'admin','request.assign',{id:'request-a',version:0,assigneeId:'south-agent'}),400);
 state=save(state,'admin','request.assign',{id:'request-a',version:0,assigneeId:'north-agent'});
 assert.equal(state.requests[0].assignedTo,'north-agent');
 state=save(state,'admin','staff.save',{userId:'north-agent',version:0,role:'agent',officeId:'south',active:true});
 assert.equal(state.requests[0].assignedTo,null);
 state=save(state,'admin','customer.membership.save',{userId:'customer-a',version:0,companyId:'company-b',active:true});
 assert.deepEqual(previewSnapshot(state,'customer-a').requests.map(x=>x.id),['request-b']);
 denied(()=>save(state,'customer-a','request.comment',{id:'request-a',version:2,body:'old company'}),404);
 denied(()=>save(state,'admin','office.save',{id:'north',version:0,name:'North',active:false}),409);
});
test('new documents stay private; review/share respects parent, edit withdrawal and archive/restore',()=>{
 let state=save(initialPreviewState(),'north-agent','order.create',{requestId:'request-a'});const orderId=state.orders[0].id;
 state=save(state,'north-agent','order.tracking',{id:orderId,version:0,label:'Synthetic event',detail:'No booking'});const eventId=state.orders[0].tracking[0].id;
 assert.equal(previewSnapshot(state,'customer-a').orders.some(x=>x.id===orderId),false);
 denied(()=>save(state,'north-agent','document.review',{kind:'order',id:orderId,version:1,note:'Not admin'}),403);
 denied(()=>save(state,'admin','document.publish',{kind:'order',id:orderId,version:1}),409);
 state=save(state,'admin','document.review',{kind:'tracking',id:eventId,version:0,note:'Private synthetic evidence'});
 denied(()=>save(state,'admin','document.publish',{kind:'tracking',id:eventId,version:1}),409);
 state=save(state,'admin','document.review',{kind:'order',id:orderId,version:1,note:'Reviewed draft only'});
 state=save(state,'admin','document.publish',{kind:'order',id:orderId,version:2});
 state=save(state,'admin','document.review',{kind:'tracking',id:eventId,version:1,note:'Private synthetic evidence'});
 state=save(state,'admin','document.publish',{kind:'tracking',id:eventId,version:2});
 assert.equal(previewSnapshot(state,'customer-a').orders.find(x=>x.id===orderId).tracking.length,1);
 assert.equal(JSON.stringify(previewSnapshot(state,'customer-a')).includes('Private synthetic evidence'),false);
 const command=operation('order.update',{id:orderId,version:3,status:'Draft',shippingNote:'Changed'});
 const changed=applyPreviewCommand(state,'north-agent',command);state=changed.state;
 assert.equal(previewSnapshot(state,'customer-a').orders.some(x=>x.id===orderId),false);
 assert.equal(state.orders[0].tracking[0].customerVisible,false);
 state=save(state,'admin','document.archive',{kind:'order',id:orderId,version:4});
 denied(()=>save(state,'north-agent','order.update',{id:orderId,version:5,status:'Draft',shippingNote:''}),409);
 state=save(state,'admin','document.restore',{kind:'order',id:orderId,version:5});
 assert.equal(state.orders[0].customerVisible,false);assert.equal(state.orders[0].reviewVersion,null);
 assert.equal(applyPreviewCommand(state,'north-agent',command).repeated,true);
});
test('sharing config fails closed and canonical commands do not accept caller policy or private file links',()=>{
 assert.equal(documentPolicy({}),null);
 for(const policy of ['', '{}','{"reference":"x","allow":{"order":"true"}}','{"reference":"x","allow":{"order":true,"payment":true}}'])assert.equal(documentPolicy({CPS_DOCUMENT_VISIBILITY_ENABLED:'true',CPS_DOCUMENT_POLICY_JSON:policy}),null);
 const policy=documentPolicy({CPS_DOCUMENT_VISIBILITY_ENABLED:'true',CPS_DOCUMENT_POLICY_JSON:'{"reference":"fixture","allow":{"order":true}}'});assert.deepEqual(policy,{reference:'fixture',kinds:['order']});
 const admin={mode:'staff',role:'admin'},id=randomUUID();
 denied(()=>validateWorkspaceCommand({key:id,type:'document.publish',input:{kind:'order',id,version:0,policy}},admin),503);
 denied(()=>validateWorkspaceCommand({key:id,type:'document.publish',input:{kind:'invoice',id,version:0}},admin,{documents:policy}),503);
 denied(()=>validateWorkspaceCommand({key:id,type:'catalogue.save',input:{imageAsset:'https://private/file'}},admin),400);
 assert.deepEqual(catalogueFilters({q:'  filter  ',page:'2',brand:'A & B'}),{q:'filter',page:2,brand:'A & B',category:''});
 for(const params of [{q:['x','y']},{q:'x'.repeat(81)},{page:'-1'},{page:'10001'},{page:'1.5'}])denied(()=>catalogueFilters(params),400);
});
