// Called only inside this invocation's isolated synthetic database.
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {writeFileSync}=require('node:fs');
module.exports=async function(f){
 const {sql,asUser,fixture,agent,other,admin,disabled,customerA,customerB,inactive,companyA,companyB,requestA,officeA,officeB,id}=f;
 const {writeWorkspaceCommand}=await import('../lib/workspace-writer.mjs');
 const {readWorkspaceAdministration}=await import('../lib/workspace-administration.mjs');
 const {readWorkspaceResource}=await import('../lib/workspace-reader.mjs');
 const {readCatalogue,readCatalogueDetail}=await import('../lib/catalogue-reader.mjs');
 const make=(type,input,key=randomUUID())=>({type,input,key});
 const save=(actor,type,input,options={},key)=>writeWorkspaceCommand(fixture.client(actor),fixture.service,'staff',make(type,input,key),options);
 const deny=(promise,status)=>assert.rejects(promise,e=>e.status===status);
 let privileged=0;for(const actor of ['missing',customerA,agent,disabled])await deny(readWorkspaceAdministration(fixture.client(actor),()=>{privileged++;return fixture.service()}),actor==='missing'?401:403);assert.equal(privileged,0);
 const roster=await readWorkspaceAdministration(fixture.client(admin),fixture.service);assert.equal(roster.staff.find(x=>x.id===agent).officeId,officeA);assert.equal(JSON.stringify(roster).includes('object_key'),false);
 assert.throws(()=>asUser(admin,`select public.cps_admin_snapshot('${admin}',0);`),/permission denied/);
 await deny(save(agent,'office.save',{name:'Bypass',active:false}),403);
 const newOffice=await save(admin,'office.save',{name:'Synthetic inactive office',active:false});
 await deny(save(admin,'company.create',{name:'Denied company',officeId:newOffice.id}),400);
 await deny(save(admin,'office.save',{id:officeA,version:0,name:'Still in use',active:false}),409);
 await deny(save(admin,'staff.save',{userId:admin,version:0,label:'',role:'agent',officeId:officeA,active:true}),409);
 await deny(save(admin,'staff.save',{userId:randomUUID(),version:null,label:'',role:'agent',officeId:officeA,active:false}),400);
 const staffVersion=()=>Number(sql(`select version from public.cps_staff_members where user_id='${agent}';`));
 const assignmentVersion=()=>Number(sql(`select version from public.cps_portal_requests where id='${requestA}';`));
 await deny(save(admin,'request.assign',{id:requestA,version:assignmentVersion(),assigneeId:other}),400);
 const key=randomUUID(),input={id:requestA,version:assignmentVersion(),assigneeId:agent};
 const assigned=await Promise.all(Array.from({length:5},()=>save(admin,'request.assign',input,{},key)));assert.equal(assigned.filter(x=>!x.repeated).length,1);assert.equal(sql(`select count(*) from public.cps_workspace_audit where resource_id='${requestA}' and operation='request.assign';`),'1');
 await deny(save(admin,'request.assign',input),409);
 await save(admin,'staff.save',{userId:agent,version:staffVersion(),role:'agent',officeId:officeB,active:true,label:'Moved synthetic agent'});
 assert.equal(sql(`select assigned_to is null from public.cps_portal_requests where id='${requestA}';`),'t');
 assert.equal((await readWorkspaceResource(fixture.client(agent),'staff','requests')).rows.every(x=>x.company_id===companyB),true);
 await save(admin,'staff.save',{userId:agent,version:staffVersion(),role:'agent',officeId:officeA,active:false,label:''});
 await deny(readWorkspaceResource(fixture.client(agent),'staff','requests'),403);
 await save(admin,'staff.save',{userId:agent,version:staffVersion(),role:'agent',officeId:officeA,active:true,label:''});
 const customerVersion=()=>Number(sql(`select version from public.cps_customer_members where user_id='${customerA}';`));
 const customerSave=input=>writeWorkspaceCommand(fixture.client(admin),fixture.service,'staff',make('customer.membership.save',input));
 await customerSave({userId:customerA,version:customerVersion(),companyId:companyB,active:true,label:'Company B fixture'});
 assert.equal((await readWorkspaceResource(fixture.client(customerA),'customer','requests')).rows.every(x=>x.company_id===companyB),true);
 await deny(writeWorkspaceCommand(fixture.client(customerA),fixture.service,'customer',make('request.comment',{id:requestA,version:assignmentVersion(),body:'Old company'})),404);
 await customerSave({userId:customerA,version:customerVersion(),companyId:companyA,active:true,label:''});
 // Guest attachments move with office RLS; assignment never grants customer ownership.
 const rfqVersion=()=>Number(sql(`select status_version from public.cps_rfqs where id='${id}';`));
 await deny(save(admin,'rfq.assign',{id,version:rfqVersion(),officeId:officeB,assigneeId:agent}),400);
 await save(admin,'rfq.assign',{id,version:rfqVersion(),officeId:officeB,assigneeId:other});
 assert.equal(asUser(agent,`select count(*) from public.cps_attachments where rfq_id='${id}';`),'0');
 assert.equal(asUser(other,`select count(*) from public.cps_attachments where rfq_id='${id}';`),'1');
 assert.equal(asUser(customerA,'select count(*) from public.cps_attachments;'),'0');
 await save(admin,'rfq.assign',{id,version:rfqVersion(),officeId:officeA,assigneeId:null});
 const order=await save(agent,'order.create',{requestId:requestA});
 const options={documents:{reference:'synthetic-reviewed-policy',kinds:['order','invoice','tracking']}};
 const version=(table,rid)=>Number(sql(`select version from public.${table} where id='${rid}';`));
 const doc=(type,kind,rid,table,actor=admin)=>save(actor,type,{kind,id:rid,version:version(table,rid),note:'PRIVATE REVIEW EVIDENCE'},options);
 await deny(save(admin,'document.publish',{kind:'order',id:order.id,version:0}),503);
 await deny(doc('document.review','order',order.id,'cps_order_drafts',agent),403);
 await doc('document.review','order',order.id,'cps_order_drafts');await doc('document.publish','order',order.id,'cps_order_drafts');
 assert.equal(asUser(customerA,`select count(*) from public.cps_order_drafts where id='${order.id}';`),'1');
 assert.equal(asUser(customerA,'select count(*) from public.cps_document_reviews;'),'0');assert.equal(asUser(other,'select count(*) from public.cps_document_reviews;'),'0');
 const editKey=randomUUID(),editInput={id:order.id,version:2,status:'Ready for internal review',shippingNote:'Synthetic note'};
 await save(agent,'order.update',editInput,{},editKey);
 const invoice=await save(agent,'invoice.save',{orderId:order.id,currency:'AED',scale:2,taxMinor:null,lines:[{description:'Synthetic amount',quantity:1,unitMinor:100}]});
 await doc('document.review','invoice',invoice.id,'cps_invoice_drafts');await deny(doc('document.publish','invoice',invoice.id,'cps_invoice_drafts'),409);
 await doc('document.review','order',order.id,'cps_order_drafts');await doc('document.publish','order',order.id,'cps_order_drafts');
 // Parent review withdraws child review, so a fresh child review is required.
 await deny(doc('document.publish','invoice',invoice.id,'cps_invoice_drafts'),409);
 await doc('document.review','invoice',invoice.id,'cps_invoice_drafts');await doc('document.publish','invoice',invoice.id,'cps_invoice_drafts');
 assert.equal(asUser(customerA,`select count(*) from public.cps_invoice_drafts where id='${invoice.id}';`),'1');
 assert.equal((await save(agent,'order.update',editInput,{},editKey)).repeated,true);
 assert.equal(sql(`select customer_visible from public.cps_invoice_drafts where id='${invoice.id}';`),'t');
 // Race a reviewed child's publication against a parent edit. Both commit safely,
 // with withdrawal final regardless of transaction order; locks prevent re-sharing.
 await doc('document.review','invoice',invoice.id,'cps_invoice_drafts');
 const race=await Promise.allSettled([doc('document.publish','invoice',invoice.id,'cps_invoice_drafts'),save(agent,'order.update',{id:order.id,version:version('cps_order_drafts',order.id),status:'Draft',shippingNote:'Concurrent changed'})]);
 assert.equal(race[1].status,'fulfilled');if(race[0].status==='rejected')assert.equal(race[0].reason.status,409);
 assert.equal(sql(`select customer_visible from public.cps_invoice_drafts where id='${invoice.id}';`),'f');
 await doc('document.archive','order',order.id,'cps_order_drafts');await deny(save(agent,'order.update',{id:order.id,version:version('cps_order_drafts',order.id),status:'Draft',shippingNote:''}),409);await doc('document.restore','order',order.id,'cps_order_drafts');
 assert.equal(sql(`select customer_visible from public.cps_order_drafts where id='${order.id}';`),'f');
 await save(agent,'order.tracking',{id:order.id,version:version('cps_order_drafts',order.id),label:'Synthetic review event',detail:'No shipment booked'});
 const eventId=sql(`select id from public.cps_tracking_events where order_id='${order.id}';`);
 await doc('document.review','tracking',eventId,'cps_tracking_events');await deny(doc('document.publish','tracking',eventId,'cps_tracking_events'),409);
 await doc('document.review','order',order.id,'cps_order_drafts');await doc('document.publish','order',order.id,'cps_order_drafts');
 await doc('document.review','tracking',eventId,'cps_tracking_events');await doc('document.publish','tracking',eventId,'cps_tracking_events');
 assert.equal(asUser(customerA,`select count(*) from public.cps_tracking_events where id='${eventId}';`),'1');
 await doc('document.unpublish','order',order.id,'cps_order_drafts');assert.equal(asUser(customerA,`select count(*) from public.cps_tracking_events where id='${eventId}';`),'0');
 // Two administrators cannot concurrently demote each other into zero admins.
 const staffVersionOf=rid=>Number(sql(`select version from public.cps_staff_members where user_id='${rid}';`));
 await save(admin,'staff.save',{userId:disabled,version:staffVersionOf(disabled),role:'admin',officeId:null,active:true,label:'Synthetic second admin'});
 const roles=await Promise.allSettled([save(admin,'staff.save',{userId:disabled,version:staffVersionOf(disabled),role:'agent',officeId:officeA,active:true,label:''}),save(disabled,'staff.save',{userId:admin,version:staffVersionOf(admin),role:'agent',officeId:officeA,active:true,label:''})]);
 assert.equal(roles.filter(x=>x.status==='fulfilled').length,1);assert.equal(roles.find(x=>x.status==='rejected').reason.status,403);
 assert.equal(sql("select count(*) from public.cps_staff_members where role='admin' and active;"),'1');
 const survivor=sql("select user_id from public.cps_staff_members where role='admin' and active;");
 if(survivor!==admin)await save(survivor,'staff.save',{userId:admin,version:staffVersionOf(admin),role:'admin',officeId:null,active:true,label:''});
 await save(admin,'staff.save',{userId:disabled,version:staffVersionOf(disabled),role:'admin',officeId:null,active:false,label:''});
 // Search, pagination, safe illustrations and detail use the anonymous SDK/RLS.
 const catalogueIds=Array.from({length:14},()=>randomUUID());for(const rid of catalogueIds)sql(`insert into public.cps_catalogue(id,title,part_number,brand,category,description,published,approved,approved_version,image_asset) values('${rid}','Synthetic search filter','SAMPLE','Fixture Make','Filter & Seal','Synthetic only',true,true,0,'/parts-catalogue.png');`);
 const anonymous=fixture.client(fixture.publicKey);
 const page=await readCatalogue(anonymous,{q:'filter',category:'Filter & Seal',brand:'Fixture Make'});assert.equal(page.rows.length,12);assert.equal(page.hasMore,true);assert.ok(page.facets.brands.includes('Fixture Make'));
 const second=await readCatalogue(anonymous,{q:'filter',category:'Filter & Seal',page:'1'});assert.equal(second.rows.length,2);assert.equal(page.rows.some(x=>second.rows.some(y=>x.id===y.id)),false);
 const detail=await readCatalogueDetail(anonymous,catalogueIds[0]);assert.equal(detail.image_asset,'/parts-catalogue.png');
 sql(`update public.cps_catalogue set published=false where id='${detail.id}';`);await deny(readCatalogueDetail(anonymous,detail.id),404);
 await deny(readCatalogueDetail(anonymous,'object/key'),404);
 const result={passed:true,liveProvider:false,checks:['administrator-only roster; no privileged client before verification','self-demotion, missing account, inactive office, stale version denied','concurrent assignment retries one audit','reassignment revokes old office/company access and clears invalid queues','guest attachments follow current office; customer denied','private default; explicit review and policy required','private review evidence denied to customer/cross-office dual-role','parent-first locks serialize sharing/edit and withdraw children','idempotent old edit cannot withdraw later sharing','archive/restore private; issuance unchanged','anonymous indexed catalogue search/facets/pagination/detail/withdrawal']};
 writeFileSync('evidence/administration-provider-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
};
