const assert = require('node:assert/strict');
const {mkdir,writeFile} = require('node:fs/promises');
const {chromium} = require(process.env.CPS_PLAYWRIGHT_MODULE || 'playwright');
const base=process.env.CPS_BASE_URL||'http://127.0.0.1:4317';
const target=new URL(base);assert.equal(target.protocol,'http:');assert.ok(['127.0.0.1','localhost','[::1]'].includes(target.hostname),'Local fixture only');
(async()=>{
  await mkdir('evidence',{recursive:true});
  const browser=await chromium.launch({headless:true,executablePath:process.env.CPS_CHROMIUM_PATH});
  try {
    const page=await browser.newPage({viewport:{width:1280,height:960}});
    page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(120000);
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`${base}/request`);
    await page.getByLabel('Full name', {exact:false}).waitFor();
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByText('Please correct the marked fields.').waitFor();
    await page.waitForFunction(()=>document.activeElement.id==='name');
    assert.equal(await page.evaluate(()=>document.activeElement.id),'name');
    assert.equal(await page.getByLabel('Full name',{exact:false}).getAttribute('required'),'');
    assert.equal(await page.getByLabel('Email',{exact:true}).getAttribute('required'),null);
    await page.getByLabel('Full name',{exact:false}).fill('Synthetic QA Workshop');
    await page.getByLabel('Email',{exact:true}).fill('qa@example.test');
    await page.getByLabel(/^Country/).fill('Qatar');
    await page.getByLabel('Save this draft').check();
    await page.screenshot({path:'evidence/rfq-desktop.png',fullPage:true});
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByLabel('Vehicle or equipment category',{exact:false}).selectOption('Truck or Trailer');
    await page.getByLabel(/^Brand/).fill('Dongfeng');
    await page.getByRole('button',{name:'Back',exact:true}).click();
    assert.equal(await page.getByLabel('Full name',{exact:false}).inputValue(),'Synthetic QA Workshop');
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    assert.equal(await page.getByLabel(/^Brand/).inputValue(),'Dongfeng');
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByLabel('Part description',{exact:true}).fill('Oil filter <synthetic QA>');
    await page.getByLabel('Quantity',{exact:false}).fill('2');
    await page.reload();
    assert.equal(await page.getByLabel('Part description',{exact:true}).inputValue(),'Oil filter <synthetic QA>');
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByLabel('Choose attachments',{exact:true}).setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aVDsAAAAASUVORK5CYII=','base64')});
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByRole('heading',{name:'Review your request',exact:true}).waitFor();
    assert.ok((await page.locator('.request-review').innerText()).includes('Oil filter <synthetic QA>'));
    assert.ok((await page.locator('.request-review').innerText()).includes('synthetic.png'));
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'evidence/rfq-mobile-review.png',fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');
    let releaseFailure,signalIntercepted;
    const intercepted=new Promise(resolve=>{signalIntercepted=resolve;});
    await page.route('**/api/rfq',async route=>{await new Promise(resolve=>{releaseFailure=resolve;signalIntercepted();});await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Synthetic storage unavailable. Please retry.'})});});
    await page.getByRole('button',{name:'Save local test request',exact:true}).click();
    await page.getByRole('button',{name:/Saving request/}).waitFor();
    await intercepted;
    for(const button of await page.locator('.request-review button').all())assert.equal(await button.isDisabled(),true);
    releaseFailure();
    await page.getByText('Synthetic storage unavailable. Please retry.').waitFor();
    assert.match(await page.locator('.request-review').innerText(),/Oil filter <synthetic QA>/);
    await page.unroute('**/api/rfq');
    await page.getByRole('button',{name:'Save local test request',exact:true}).click();
    await page.getByRole('heading',{name:'Your test request is saved'}).waitFor();
    const reference=await page.locator('.request-success strong').innerText();assert.match(reference,/^CPS-LOCAL-/);
    assert.equal(await page.evaluate(()=>localStorage.getItem('cps-rfq-draft')),null);
    assert.deepEqual(errors,[]);
    const denied=await page.request.post(`${base}/api/rfq`,{headers:{origin:'https://unrelated.example'},multipart:{data:'{}',submissionId:crypto.randomUUID()}});
    assert.equal(denied.status(),403);
    const malformed=await page.request.post(`${base}/api/rfq`,{headers:{origin:base},multipart:{data:'{}',submissionId:crypto.randomUUID()}});
    assert.equal(malformed.status(),400);
    const disguised=await page.request.post(`${base}/api/rfq`,{headers:{origin:base},multipart:{data:JSON.stringify({...require('../lib/rfq.mjs').blank,name:'Synthetic',country:'Qatar',email:'qa@example.test',category:'Truck',description:'QA',quantity:'1'}),submissionId:crypto.randomUUID(),attachments:{name:'bad.png',mimeType:'image/png',buffer:Buffer.from('<html>')}}});
    assert.equal(disguised.status(),400);
    const payload={...require('../lib/rfq.mjs').blank,name:'Concurrent QA',country:'Qatar',email:'qa@example.test',category:'Truck',description:'Concurrent synthetic',quantity:'1'},submissionId=crypto.randomUUID();
    const responses=await Promise.all(Array.from({length:6},()=>page.request.post(`${base}/api/rfq`,{headers:{origin:base},multipart:{data:JSON.stringify(payload),submissionId}})));
    assert.ok(responses.every(response=>response.status()===201));
    const refs=await Promise.all(responses.map(response=>response.json()));assert.equal(new Set(refs.map(row=>row.reference)).size,1);
    const conflict=await page.request.post(`${base}/api/rfq`,{headers:{origin:base},multipart:{data:JSON.stringify({...payload,quantity:'2'}),submissionId}});assert.equal(conflict.status(),409);
    const oversized=await page.request.post(`${base}/api/rfq`,{headers:{origin:base},multipart:{data:JSON.stringify(payload),submissionId:crypto.randomUUID(),attachments:{name:'large.pdf',mimeType:'application/pdf',buffer:Buffer.alloc(5*1024*1024+1)}}});assert.equal(oversized.status(),400);
    const download=await page.request.get(`${base}/api/staff/attachments/${crypto.randomUUID()}`);assert.equal(download.status(),503);
    await page.goto(`${base}/staff`);await page.waitForURL('**/staff/login?error=access');assert.ok((await page.locator('body').innerText()).includes('not configured'));
    await page.goto(base);
    await page.getByRole('button',{name:'Start your RFQ'}).click();
    await page.waitForURL('**/request');
    await page.setViewportSize({width:1280,height:960});
    await page.goto(base);await page.locator('.portal').click();await page.waitForURL('**/customer-access');
    await page.goto(base);
    assert.equal(await page.locator('.header-search,.finder,.products,.browse-discovery,.quick-browse,.popular-searches').count(),0);
    await page.locator('.brand-tile').first().click();await page.waitForURL('**/request?part=Dongfeng');
    assert.equal(await page.getByLabel('Part description',{exact:false}).count(),0); // starts with contact step
    assert.match(page.url(),/part=Dongfeng/);
    await page.goto(base);await page.locator('.category').first().click();
    await page.waitForURL('**/request?part=Passenger*');
    assert.match(page.url(),/Passenger%20Vehicle%20Parts/);
    await page.goto(base+'/request');
    await page.getByLabel('Full name',{exact:false}).fill('Phone-only synthetic QA');
    await page.getByLabel(/^Country/).fill('Qatar');
    await page.getByLabel('Telephone with country code',{exact:true}).fill('+974 1234 5678');
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByLabel('Vehicle or equipment category',{exact:false}).selectOption('Other');
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByLabel('OEM number',{exact:true}).fill('QA-OEM-123');
    await page.getByRole('button',{name:'Continue',exact:true}).click();
    await page.getByRole('heading',{name:'Attachments',exact:true}).waitFor();
    const result={date:new Date().toISOString().slice(0,10),passed:true,reference,checks:['required fields and first-invalid focus','contact method alternatives and native required semantics','phone-only and OEM-only request with optional equipment details','back and next retention','reload restoration','actual review','pending review editing disabled','save failure preserves draft and retry succeeds','attachment save','mobile overflow','draft cleared on success','foreign origin rejected','malformed payload rejected','disguised upload rejected','website RFQ navigation','six concurrent HTTP submissions converge','conflicting HTTP reuse rejected','oversized upload rejected','staff/download setup fails closed','desktop portal routes to unavailable-state screen','sparse catalogue/search presentation hidden','brand and category selections preserved in RFQ URL'],screenshots:['evidence/rfq-desktop.png','evidence/rfq-mobile-review.png']};
    await writeFile('evidence/browser-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1});
