'use client';
import ScopedSelector from './ScopedSelector';
import {useState} from 'react';
import {Field,WorkspaceForm, type Mutate} from './WorkspaceForms';
import {useWorkspaceEnvironment} from './WorkspaceEnvironment';
import type {PreviewSnapshot,AdministrationSnapshot} from '../../lib/preview-domain.mjs';
export default function AdministrationWorkspace({snapshot,data,mutate,pending,page,onPage}:{snapshot:PreviewSnapshot;data:AdministrationSnapshot;mutate:Mutate;pending:boolean;page:number;onPage:(page:number)=>void}){
 const {live}=useWorkspaceEnvironment();const [tab,setTab]=useState('offices'),[selected,setSelected]=useState('');
 const rows=tab==='offices'?data.offices:tab==='staff'?data.staff:tab==='members'?data.members:data.rfqs;
 const record=rows.find(item=>item.id===selected);const v=(f:FormData,key:string)=>String(f.get(key)??'');
 const staff=tab==='staff'?data.staff.find(item=>item.id===selected):undefined,member=tab==='members'?data.members.find(item=>item.id===selected):undefined,rfq=tab==='assignments'?data.rfqs.find(item=>item.id===selected):undefined,office=tab==='offices'?data.offices.find(item=>item.id===selected):undefined;
 const officeSelect=(value?:string|null,required=true)=><ScopedSelector kind="offices" name="officeId" required={required} defaultValue={value??''} options={data.offices.filter(row=>row.active).map(row=>({id:row.id,label:row.name}))}/>;
 const account=(value?:string)=>live?<input required name="userId" defaultValue={value} maxLength={36} placeholder="Existing provider user UUID" readOnly={!!value}/>:<select name="userId" defaultValue={value??''} required><option value="">Select an existing demo account</option>{(tab==='staff'?['admin','north-agent','south-agent']:['customer-a','customer-b']).map(id=><option key={id}>{id}</option>)}</select>;
 return <><section className="ws-panel"><h2>Access and assignment administration</h2><p className="ws-muted">Manage existing account memberships. This does not create credentials, send invitations or grant access through an assignment. Another administrator must change your own role or active state.</p><div className="ws-actions">{[['offices','Offices'],['staff','Staff access'],['members','Company access'],['assignments','Guest assignments']].map(([key,label])=><button type="button" className="ws-secondary" disabled={pending} aria-pressed={tab===key} key={key} onClick={()=>{setTab(key);setSelected('')}}>{label}</button>)}</div>{live&&<div className="ws-actions"><button className="ws-secondary" disabled={pending||page===0} onClick={()=>onPage(page-1)}>Previous roster page</button><span>Page {page+1} · up to 50 per roster</span><button className="ws-secondary" disabled={pending||!rows.length||rows.length<50} onClick={()=>onPage(page+1)}>Next roster page</button></div>}<div className="ws-record-layout"><section><button className="ws-secondary" disabled={pending||tab==='assignments'} onClick={()=>setSelected('')}>New membership / office</button><ul className="ws-select-list">{rows.map(item=><li key={item.id}><button disabled={pending} aria-pressed={item.id===selected} onClick={()=>setSelected(item.id)}><strong>{'name'in item?item.name:'reference'in item?item.reference:'label'in item&&item.label?item.label:item.id}</strong><small>{'active'in item?(item.active?'Active':'Inactive'):'Assignment review'}</small></button></li>)}</ul>{!rows.length&&<p className="ws-empty">No records on this page.</p>}</section><section key={`${tab}:${selected}:${record?.version??'new'}`}>
 {tab==='offices'&&<WorkspaceForm pending={pending} onSave={f=>mutate('office.save',{id:office?.id,version:office?.version,name:v(f,'name'),active:f.get('active')==='on'})}><h3>{office?'Review office':'New office'}</h3><Field label="Office label"><input name="name" required maxLength={200} defaultValue={office?.name}/></Field><Field label="Active office"><input name="active" type="checkbox" defaultChecked={office?.active??false}/></Field><p className="ws-muted">An office in use cannot be deactivated. Existing scope labels must be reviewed before activation.</p></WorkspaceForm>}
 {tab==='staff'&&<WorkspaceForm pending={pending} onSave={f=>mutate('staff.save',{userId:v(f,'userId'),version:staff?.version??null,label:v(f,'label'),role:v(f,'role'),officeId:v(f,'officeId')||null,active:f.get('active')==='on'})}><h3>Staff membership</h3><Field label={live?'Existing provider account ID':'Demo account'}>{account(staff?.userId)}</Field><Field label="Account label"><input name="label" maxLength={100} defaultValue={staff?.label}/></Field><Field label="Staff role"><select name="role" defaultValue={staff?.role??'agent'}><option value="agent">Office agent</option><option value="admin">Administrator</option></select></Field><Field label="Agent office">{officeSelect(staff?.officeId,false)}</Field><Field label="Active staff access"><input name="active" type="checkbox" defaultChecked={staff?.active??false}/></Field><p className="ws-muted">The selected office applies to agents. Administrator access covers all offices and requires an explicit review.</p></WorkspaceForm>}
 {tab==='members'&&<WorkspaceForm pending={pending} onSave={f=>mutate('customer.membership.save',{userId:v(f,'userId'),version:member?.version??null,label:v(f,'label'),companyId:v(f,'companyId'),active:f.get('active')==='on'})}><h3>Company membership</h3><Field label={live?'Existing provider account ID':'Demo account'}>{account(member?.userId)}</Field><Field label="Account label"><input name="label" maxLength={100} defaultValue={member?.label}/></Field><Field label="Company"><ScopedSelector kind="companies" name="companyId" defaultValue={member?.companyId??''} options={snapshot.customers.map(row=>({id:row.id,label:row.name}))}/></Field><Field label="Active company access"><input name="active" type="checkbox" defaultChecked={member?.active??false}/></Field><p className="ws-muted">One company per account. Reassignment removes access to the previous company's records; it does not claim guest enquiries.</p></WorkspaceForm>}
 {tab==='assignments'&&(rfq?<WorkspaceForm pending={pending} onSave={f=>mutate('rfq.assign',{id:rfq.id,version:rfq.version,officeId:v(f,'officeId'),assigneeId:v(f,'assigneeId')||null})}><h3>{rfq.reference}</h3><Field label="Assigned office">{officeSelect(rfq.officeId)}</Field><Field label="Staff assignee"><select name="assigneeId" defaultValue={rfq.assigneeId??''}><option value="">Office queue — no individual assignee</option>{data.staff.filter(item=>item.active).map(item=><option key={item.id} value={item.userId}>{item.label||item.userId}</option>)}</select></Field><p className="ws-muted">Only active staff in the chosen office or an administrator can be assigned. Server validation enforces the boundary.</p></WorkspaceForm>:<p className="ws-empty">Select a guest RFQ. Use the parts-request screen for company request assignments.</p>)}
 </section></div></section><section className="ws-panel"><WorkspaceForm pending={pending} button="Create company record" onSave={f=>mutate('company.create',{name:v(f,'companyName'),contact:v(f,'contact'),email:v(f,'email'),officeId:v(f,'officeId')})}><h3>New company</h3><Field label="Company name"><input name="companyName" required maxLength={200}/></Field><Field label="Company contact (optional)"><input name="contact" maxLength={200}/></Field><Field label="Company email (optional)"><input name="email" type="email" maxLength={200}/></Field><Field label="Company office">{officeSelect()}</Field></WorkspaceForm></section></>;
}
