'use client';
import {useWorkspaceEnvironment} from './WorkspaceEnvironment';
import type {ReactNode} from 'react';
import type {PreviewSnapshot,PreviewRequest,PreviewOrder,PreviewInvoice,PreviewSupport,PartLine} from '../../lib/preview-domain.mjs';
export function Empty({children}:{children:ReactNode}){return <p className="ws-empty">{children}</p>}
export function PartSummary({items}:{items:PartLine[]}){return <ul className="ws-parts-summary">{items.map((item,index)=><li key={index}><div><strong>{item.description}</strong><small>{item.partNumber||'Part number not supplied'}</small></div><b>× {item.quantity}</b></li>)}</ul>}
export function Comments({comments}:{comments:{id:string;body:string;author:string;visibility?:string;createdAt:string}[]}){return <div className="ws-conversation">{comments.length?comments.map(comment=><article key={comment.id}><div><strong>{comment.author}</strong><small>{comment.visibility==='internal'?'Staff only':new Date(comment.createdAt).toLocaleString()}</small></div><p>{comment.body}</p></article>):<Empty>No comments yet.</Empty>}</div>}
export function RequestDetail({record}:{record:PreviewRequest}){return <><div className="ws-detail-head"><span className="ws-tag">{record.status}</span><h2>{record.reference}</h2></div><PartSummary items={record.items}/>{record.requirementContext&&Object.keys(record.requirementContext).length>0&&<dl className="ws-integrations">{Object.entries(record.requirementContext).map(([key,value])=><div key={key}><dt>{key}</dt><dd className="ws-message-body">{value}</dd></div>)}</dl>}<Comments comments={record.comments}/></>}
export function OrderDetail({record}:{record:PreviewOrder}){return <><div className="ws-detail-head"><span className="ws-tag">{record.status}</span><h2>{record.reference}</h2></div><PartSummary items={record.items}/><p className="ws-muted">{record.shippingNote||'Shipping terms awaiting review.'}</p><h3>Tracking timeline</h3>{record.tracking.length?<ol className="ws-timeline">{record.tracking.map(event=><li key={event.id}><small>{new Date(event.createdAt).toLocaleString()}</small><strong>{event.label}</strong><p>{event.detail}</p></li>)}</ol>:<Empty>No tracking events recorded.</Empty>}</>}
export function money(minor:number,currency:string,scale:number|null){if(scale===null)return `${currency} ${minor} minor units (precision unavailable)`;return `${currency} ${(minor/10**scale).toFixed(scale)}`}
export function InvoiceDetail({record,snapshot}:{record:PreviewInvoice;snapshot:PreviewSnapshot}){const {live}=useWorkspaceEnvironment();const company=snapshot.customers.find(customer=>customer.id===record.company);return <article className="ws-invoice"><p className="ws-invoice-watermark">SYNTHETIC DRAFT — NOT A TAX INVOICE</p><h2>{record.reference}</h2><p>{company?.name??(live?'Company':'Synthetic company')} · {record.status}</p><div className="ws-invoice-lines">{record.lines.map((line,index)=><div key={index}><span>{line.description}<small>Quantity {line.quantity} · {money(line.unitMinor,record.currency,record.scale)} each</small></span><strong>{money(line.quantity*line.unitMinor,record.currency,record.scale)}</strong></div>)}</div><dl className="ws-totals"><div><dt>Subtotal</dt><dd>{money(record.totals.subtotal,record.currency,record.scale)}</dd></div><div><dt>Draft tax amount</dt><dd>{record.totals.tax===null?'Unconfigured':money(record.totals.tax,record.currency,record.scale)}</dd></div><div><dt>Draft total</dt><dd>{record.totals.total===null?'Awaiting tax review':money(record.totals.total,record.currency,record.scale)}</dd></div></dl><p className="ws-muted">No legal invoice number, tax registration or payment demand has been issued. {!live&&'These values are synthetic.'}</p><div className="ws-actions ws-no-print"><button type="button" className="ws-secondary" onClick={()=>window.print()}>Print draft</button><button type="button" className="ws-secondary" disabled>Issue invoice — setup required</button></div></article>}
export function SupportDetail({record}:{record:PreviewSupport}){return <><span className="ws-tag">{record.status}</span><h2>{record.subject}</h2><p className="ws-message-body">{record.body}</p><Comments comments={record.replies}/></>}
export function IntegrationPanel({snapshot}:{snapshot:PreviewSnapshot}){return <dl className="ws-integrations">{Object.entries(snapshot.integrations).map(([key,status])=><div key={key}><dt>{key}</dt><dd>{status}</dd></div>)}</dl>}
