'use client';
import ScopedSelector from './ScopedSelector';
import {useWorkspaceEnvironment} from './WorkspaceEnvironment';
import {catalogueAssets} from '../../lib/catalogue-assets.mjs';
import {useState,useId,cloneElement,isValidElement} from 'react';
import type {FormEvent, ReactNode,ReactElement} from 'react';
import type {PreviewSnapshot,PreviewRequest,PreviewProduct,PreviewOrder,PreviewInvoice,PreviewSupport,PreviewContent,PreviewCustomer,PartLine} from '../../lib/preview-domain.mjs';

// Procurement workbench: the requirement/action leads; native controls, inset
// fields and 4px spacing share the existing Manrope/red/yellow CPS direction.
export type Mutate=(type:string,input:Record<string,unknown>)=>Promise<boolean>;
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){const id=useId();return <div className="ws-field"><label htmlFor={id}>{label}</label>{isValidElement(children)?cloneElement(children as ReactElement<{id?:string;'aria-describedby'?:string}>,{id,'aria-describedby':hint?id+'-hint':undefined}):children}{hint&&<small id={id+'-hint'}>{hint}</small>}</div>}
function Form({children,onSave,pending,button}:{children:ReactNode;onSave:(data:FormData)=>Promise<boolean>;pending:boolean;button?:string}){
  const {live}=useWorkspaceEnvironment();
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();await onSave(new FormData(event.currentTarget));}
  return <form className="ws-form" onSubmit={submit}><fieldset disabled={pending}>{children}<button className="ws-primary" type="submit">{pending?'Saving…':button??(live?'Save draft':'Save local draft')}</button></fieldset></form>;
}
const value=(data:FormData,key:string)=>String(data.get(key)??'');
export {Form as WorkspaceForm};
export function PartLines({items,setItems}:{items:PartLine[];setItems:(items:PartLine[])=>void}){
  return <div className="ws-lines">{items.map((item,index)=><div className="ws-part-line" key={index}><Field label={`Part ${index+1} description`}><input required maxLength={300} value={item.description} onChange={e=>setItems(items.map((row,i)=>i===index?{...row,description:e.target.value}:row))}/></Field><Field label={`Part ${index+1} number (optional)`}><input maxLength={100} value={item.partNumber} onChange={e=>setItems(items.map((row,i)=>i===index?{...row,partNumber:e.target.value}:row))}/></Field><Field label={`Part ${index+1} quantity`}><input required type="number" min={1} max={999999} step={1} value={item.quantity} onChange={e=>setItems(items.map((row,i)=>i===index?{...row,quantity:Number(e.target.value)}:row))}/></Field>{items.length>1&&<button type="button" className="ws-secondary" onClick={()=>setItems(items.filter((_,i)=>i!==index))}>Remove part {index+1}</button>}</div>)}<button type="button" className="ws-secondary" disabled={items.length>=50} onClick={()=>setItems([...items,{description:'',partNumber:'',quantity:1}])}>Add another part</button></div>;
}
export function RequestForm({mutate,pending,record,staff}:{mutate:Mutate;pending:boolean;record?:PreviewRequest;staff:boolean}){const {live}=useWorkspaceEnvironment();
  const [items,setItems]=useState<PartLine[]>([{description:'',partNumber:'',quantity:1}]);
  if(!record)return <Form pending={pending} button={live?'Save request':'Save synthetic request'} onSave={async()=>{const ok=await mutate('request.create',{items});if(ok)setItems([{description:'',partNumber:'',quantity:1}]);return ok;}}><h3>New parts request</h3><p className="ws-muted">Multiple parts can be reviewed together. {live?'Saving creates a requirement for staff review. It does not confirm price, availability or an order.':'This form writes only synthetic preview records.'}</p><PartLines items={items} setItems={setItems}/></Form>;
  return <>{staff&&<Form pending={pending} onSave={data=>mutate('request.update',{id:record.id,version:record.version,status:value(data,'status'),internalNote:value(data,'note')})}><h3>Internal review</h3><Field label="Review status"><select name="status" defaultValue={record.status}>{['Submitted','Under review','Needs information','Closed'].map(status=><option key={status}>{status}</option>)}</select></Field><Field label="Internal note — staff only"><textarea name="note" maxLength={2000} defaultValue={record.internalNote}/></Field></Form>}<Form pending={pending} button={live?'Add comment':'Add local comment'} onSave={data=>mutate('request.comment',{id:record.id,version:record.version,body:value(data,'body'),visibility:staff?value(data,'visibility'):'customer'})}><h3>Request conversation</h3><Field label="Comment"><textarea name="body" required maxLength={2000}/></Field>{staff&&<Field label="Visible to"><select name="visibility"><option value="customer">Customer and staff</option><option value="internal">Staff only</option></select></Field>}</Form></>;
}
export function ProductForm({record,mutate,pending}:{record?:PreviewProduct;mutate:Mutate;pending:boolean}){const {live}=useWorkspaceEnvironment();return <Form pending={pending} onSave={data=>mutate('catalogue.save',{id:record?.id,version:record?.version,title:value(data,'title'),partNumber:value(data,'partNumber'),brand:value(data,'brand'),category:value(data,'category'),description:value(data,'description'),visibility:value(data,'visibility'),imageAsset:value(data,'imageAsset')})}><h3>{record?'Edit catalogue entry':'New catalogue entry'}</h3><Field label="Product name"><input name="title" required maxLength={200} defaultValue={record?.title}/></Field><div className="ws-form-pair"><Field label="Part number (optional)"><input name="partNumber" maxLength={100} defaultValue={record?.partNumber}/></Field><Field label="Brand / equipment make (optional)"><input name="brand" maxLength={100} defaultValue={record?.brand}/></Field></div><Field label="Category"><input name="category" required maxLength={100} defaultValue={record?.category}/></Field><Field label="Description"><textarea name="description" required maxLength={2000} defaultValue={record?.description}/></Field><Field label="Managed illustration" hint="Existing process artwork only. This is not a verified product photograph."><select name="imageAsset" defaultValue={record?.imageAsset??''}>{catalogueAssets.map(asset=><option key={asset.path} value={asset.path}>{asset.label}</option>)}</select></Field>{record?.imageAsset&&<figure><img src={record.imageAsset} alt="Parts sourcing illustration" width={240}/><figcaption>Illustration only — not a product photo.</figcaption></figure>}<Field label={live?'Draft state':'Preview visibility'} hint={live?'Saving removes publication and requires review of the changed version.':'Preview makes a synthetic entry visible to preview customers. It does not publish the real catalogue.'}><select name="visibility" defaultValue={record?.visibility==='published'?'draft':record?.visibility??'draft'}><option value="draft">Staff draft</option>{!live&&<option value="preview">Customer preview</option>}<option value="archived">Archived</option></select></Field></Form>}
export function CustomerForm({record,mutate,pending}:{record:PreviewCustomer;mutate:Mutate;pending:boolean}){const {live}=useWorkspaceEnvironment();return <Form pending={pending} onSave={data=>mutate('customer.update',{id:record.id,version:record.version,contact:value(data,'contact'),note:value(data,'note')})}><h3>CRM review</h3><Field label={live?'Contact':'Synthetic contact'}><input name="contact" required maxLength={200} defaultValue={record.contact}/></Field><Field label="Internal CRM note"><textarea name="note" maxLength={2000} defaultValue={record.note}/></Field></Form>}
export function OrderForm({record,snapshot,mutate,pending}:{record?:PreviewOrder;snapshot:PreviewSnapshot;mutate:Mutate;pending:boolean}){const {live}=useWorkspaceEnvironment();
  if(!record)return <Form pending={pending} button="Create internal order draft" onSave={data=>mutate('order.create',{requestId:value(data,'requestId')})}><h3>Prepare an order draft</h3><Field label="Source request"><ScopedSelector kind="requests" name="requestId" options={snapshot.requests.map(row=>({id:row.id,label:row.reference}))}/></Field><p className="ws-muted">Creating a draft does not confirm an order, stock, price or shipping terms.</p></Form>;
  return <><Form pending={pending} onSave={data=>mutate('order.update',{id:record.id,version:record.version,status:value(data,'status'),shippingNote:value(data,'shippingNote')})}><h3>Internal order draft</h3><Field label="Draft status"><select name="status" defaultValue={record.status}><option>Draft</option><option>Ready for internal review</option></select></Field><Field label="Shipping review note"><textarea name="shippingNote" maxLength={2000} defaultValue={record.shippingNote}/></Field></Form><Form pending={pending} button={live?'Add internal tracking event':'Add synthetic tracking event'} onSave={data=>mutate('order.tracking',{id:record.id,version:record.version,label:value(data,'label'),detail:value(data,'detail')})}><h3>{live?'Internal tracking note':'Manual tracking preview'}</h3><Field label="Event title"><input required name="label" maxLength={100}/></Field><Field label="Event description"><textarea required name="detail" maxLength={1000}/></Field><p className="ws-muted">No carrier call, booking or customer notification is made. {live&&'New events remain staff-only until document visibility rules are approved.'}</p></Form></>;
}
export function InvoiceForm({record,snapshot,mutate,pending}:{record?:PreviewInvoice;snapshot:PreviewSnapshot;mutate:Mutate;pending:boolean}){const {live}=useWorkspaceEnvironment();
  const [lines,setLines]=useState(record?.lines??[{description:'',quantity:1,unitMinor:0}]);
  return <Form pending={pending} onSave={data=>mutate('invoice.save',{id:record?.id,version:record?.version,orderId:value(data,'orderId'),currency:value(data,'currency'),scale:Number(value(data,'scale')),taxMinor:value(data,'tax')===''?null:Number(value(data,'tax')),lines})}><h3>{record?'Edit invoice draft':'New invoice draft'}</h3><Field label="Order"><ScopedSelector kind="orders" name="orderId" defaultValue={record?.orderId??''} options={snapshot.orders.map(row=>({id:row.id,label:row.reference}))}/></Field><div className="ws-form-pair"><Field label="Currency code" hint="Explicit draft value; no currency is approved for live use."><input name="currency" required pattern="[A-Z]{3}" maxLength={3} defaultValue={record?.currency??''} placeholder="e.g. AED"/></Field><Field label="Currency decimal places"><input name="scale" required type="number" min={0} max={3} step={1} defaultValue={record?.scale??(live?'':2)}/></Field></div>{lines.map((line,index)=><div className="ws-part-line" key={index}><Field label={`Invoice line ${index+1}`}><input required maxLength={300} value={line.description} onChange={e=>setLines(lines.map((item,i)=>i===index?{...item,description:e.target.value}:item))}/></Field><Field label={`Line ${index+1} quantity`}><input required type="number" min={1} max={999999} step={1} value={line.quantity} onChange={e=>setLines(lines.map((item,i)=>i===index?{...item,quantity:Number(e.target.value)}:item))}/></Field><Field label={`Line ${index+1} unit amount in minor units`} hint="For two decimal places, 12500 means 125.00."><input required type="number" min={0} max={100000000} step={1} value={line.unitMinor} onChange={e=>setLines(lines.map((item,i)=>i===index?{...item,unitMinor:Number(e.target.value)}:item))}/></Field>{lines.length>1&&<button type="button" className="ws-secondary" onClick={()=>setLines(lines.filter((_,i)=>i!==index))}>Remove invoice line {index+1}</button>}</div>)}<button type="button" className="ws-secondary" disabled={lines.length>=50} onClick={()=>setLines([...lines,{description:'',quantity:1,unitMinor:0}])}>Add invoice line</button><Field label="Draft tax amount in minor units (optional)" hint="Blank means unconfigured; no payable total is displayed. Zero is an explicit draft calculation, not tax exemption."><input name="tax" type="number" min={0} max={100000000} step={1} defaultValue={record?.taxMinor??''}/></Field><p className="ws-muted">Legal entity, numbering, taxation, pricing and payment terms remain unapproved. Final issuance is disabled.</p></Form>;
}
export function SupportForm({record,staff,mutate,pending}:{record?:PreviewSupport;staff:boolean;mutate:Mutate;pending:boolean}){const {live}=useWorkspaceEnvironment();
  if(!record)return <Form pending={pending} button={live?'Save support request':'Save local support request'} onSave={data=>mutate('support.create',{subject:value(data,'subject'),body:value(data,'body')})}><h3>Ask about a request</h3><Field label="Subject"><input required name="subject" maxLength={200}/></Field><Field label="Message"><textarea required name="body" maxLength={2000}/></Field><p className="ws-muted">{live?'Saved to your company support thread. No email or WhatsApp message is sent.':'Saved in the synthetic workspace only. No email or WhatsApp message is sent.'}</p></Form>;
  return <><Form pending={pending} button={live?'Save reply':'Save local reply'} onSave={data=>mutate('support.reply',{id:record.id,version:record.version,body:value(data,'body')})}><Field label="Reply"><textarea required name="body" maxLength={2000}/></Field></Form>{staff&&<Form pending={pending} onSave={data=>mutate('support.status',{id:record.id,version:record.version,status:value(data,'status')})}><Field label="Support status"><select name="status" defaultValue={record.status}><option>Open</option><option>Under review</option><option>Closed</option></select></Field></Form>}</>;
}
export function ContentForm({record,mutate,pending}:{record?:PreviewContent;mutate:Mutate;pending:boolean}){const {live}=useWorkspaceEnvironment();return <Form pending={pending} onSave={data=>mutate('content.save',{id:record?.id,version:record?.version,title:value(data,'title'),slug:value(data,'slug'),body:value(data,'body')})}><h3>Page draft</h3><Field label="Page title"><input required name="title" maxLength={200} defaultValue={record?.title}/></Field><Field label="Page slug"><input required name="slug" pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={80} defaultValue={record?.slug}/></Field><Field label="Draft copy"><textarea required name="body" maxLength={10000} defaultValue={record?.body}/></Field><p className="ws-muted">Plain text is rendered safely. Saved drafts do not change the public site. Publication requires approved company copy.</p></Form>}
