import {notFound} from 'next/navigation';
import Link from 'next/link';
const guides:Record<string,{title:string;paragraphs:string[]}>= {
  'quality-options':{title:'Discussing part quality options',paragraphs:['Use the quality preference in your request to explain your requirements and budget. Labels alone do not establish fitment, authenticity or warranty. Ask the sourcing team to identify the manufacturer, product specification and supporting documentation for the offered part.','Confirm the exact item, compatibility, warranty and agreed terms before accepting a quotation. These details require verification for each request.']},
  'oem-number':{title:'Finding a part reference',paragraphs:['Check the existing part label, equipment nameplate and the vehicle or machine documentation. Record the reference exactly as printed, including letters, punctuation and suffixes. A clear photo can help avoid transcription mistakes.','Provide the brand, model, year and VIN or chassis reference when available. A part number by itself may not establish compatibility; ask the sourcing team to confirm the application.']},
  'request-information':{title:'Information for a useful parts request',paragraphs:['Describe the required part and quantity. Add any OEM or manufacturer reference, vehicle or equipment details, and the country where the part is needed. If you are unsure of the name, describe its location or function without making a technical compatibility claim.','Where attachments are enabled, provide clear photos of the part and nameplate. Avoid sending unrelated personal information. Bulk spreadsheet handling requires an agreed format; contact the sourcing team before sending a large list.']}
};
export function generateStaticParams(){return Object.keys(guides).map(slug=>({slug}));}
export default async function Guide({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const guide=guides[slug];if(!guide)notFound();return <main className="request-page"><article className="request-shell"><Link href="/">China Parts Shop</Link><h1>{guide.title}</h1>{guide.paragraphs.map(text=><p key={text}>{text}</p>)}<Link href="/request">Prepare a parts request</Link></article></main>;}
