import {notFound} from 'next/navigation';
import Link from 'next/link';
import PublicHeader from '../../../components/PublicHeader';
const guides:Record<string,{title:string;paragraphs:string[]}>= {
  'quality-options':{title:'Genuine, OE and OEM: ask the right questions',paragraphs:['Genuine generally refers to a part presented through the vehicle or equipment brand’s packaging and supply channel. Confirm the source and supporting documentation for the particular item.','OE describes the original-equipment producer or supplier relationship to the vehicle or equipment manufacturer. A supplier name alone does not establish that a particular part is the correct specification for your application.','OEM terminology varies by product and supplier context. Ask what the term means for the offered part, who makes it and what documentation supports it. The label alone is not an authenticity guarantee.','Genuine, OE and OEM labels do not establish fitment, availability or warranty. Confirm the exact item, manufacturer, compatibility, documentation and agreed terms with the sourcing team before accepting an offer. If unsure, select “Please advise” in your enquiry.']},
  'oem-number':{title:'Finding a part reference',paragraphs:['Check the existing part label, equipment nameplate and the vehicle or machine documentation. Record the reference exactly as printed, including letters, punctuation and suffixes. A clear photo can help avoid transcription mistakes.','Provide the brand, model, year and VIN or chassis reference when available. A part number by itself may not establish compatibility; ask the sourcing team to confirm the application.']},
  'request-information':{title:'Information for a useful parts enquiry',paragraphs:['Describe the required part and quantity. Add any OEM, OE or manufacturer reference, the vehicle or equipment brand and model, and the country where the part is needed. If unsure of the name, describe its location or function and request technical assistance.','For photos, capture the entire part, its marking or label, and the equipment nameplate in readable light. Include a separate close-up of the part number. Where uploads are enabled, the enquiry accepts bounded PNG, JPEG or PDF files. Upload availability is stated in the form; a selected file is not proof that it was received.','For a parts list, distinguish each item with its reference, description and quantity. Do not combine several numbers into one ambiguous line. Large spreadsheets need an agreed format before sharing. Use the same enquiry to describe the list if uploads are unavailable.','Common mistakes include missing number suffixes, unreadable label photos, confusing a casting mark with an orderable number, and assuming a visually similar part will fit. Provide identification details and ask the team to verify the application. Avoid unrelated personal information.']}
};
export function generateStaticParams(){return Object.keys(guides).map(slug=>({slug}));}
export default async function Guide({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const guide=guides[slug];if(!guide)notFound();return <><PublicHeader/><main className="request-page"><article className="request-shell public-guide"><h1>{guide.title}</h1>{guide.paragraphs.map(text=><p key={text}>{text}</p>)}<Link href="/request">Send Your Enquiry</Link></article></main></>;}
