import './catalogue.css';
import {publicCanonical} from '../../lib/public-index.mjs';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import {publicContentClient} from '../../lib/public-content';
import {readCatalogue} from '../../lib/catalogue-reader.mjs';
import {cataloguePhotosReady} from '../../lib/config.mjs';
import {validCatalogueAsset} from '../../lib/catalogue-assets.mjs';
export const dynamic='force-dynamic';
export function generateMetadata(){const canonical=publicCanonical('/catalogue');return {title:'Catalogue | China Parts Shop',...canonical?{alternates:{canonical}}:{}};}
export default async function Catalogue({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const client=publicContentClient();if(!client||process.env.CPS_PUBLIC_CATALOGUE_ENABLED!=='true')notFound();
 let result;try{result=await readCatalogue(client,await searchParams);}catch{return <main className="request-page catalogue-page"><section className="request-shell"><Link href="/catalogue">Reset catalogue filters</Link><h1>Parts catalogue</h1><p role="alert">The catalogue or requested filters are unavailable. Please retry.</p></section></main>;}
 const {filters,rows,facets,hasMore}=result;
 const pageHref=(page:number)=>'/catalogue?'+new URLSearchParams({q:filters.q,brand:filters.brand,category:filters.category,page:String(page)});
 return <main className="request-page catalogue-page"><section className="request-shell"><Link href="/">China Parts Shop</Link><h1>Parts catalogue</h1><p>Published descriptions help prepare an enquiry. Fitment, quality, price and availability need verification.</p><form action="/catalogue" className="catalogue-filters"><label className="ws-field">Search part details<input type="search" name="q" maxLength={80} defaultValue={filters.q} placeholder="Part number or keywords"/></label><div className="catalogue-field"><label htmlFor="catalogue-category">Category</label><select id="catalogue-category" name="category" defaultValue={filters.category}><option value="">All categories</option>{[...new Set([...facets.categories,...(filters.category?[filters.category]:[])])].map(value=><option key={value}>{value}</option>)}</select></div><div className="catalogue-field"><label htmlFor="catalogue-brand">Equipment make</label><select id="catalogue-brand" name="brand" defaultValue={filters.brand}><option value="">All makes</option>{[...new Set([...facets.brands,...(filters.brand?[filters.brand]:[])])].map(value=><option key={value}>{value}</option>)}</select></div><button type="submit" className="ws-primary">Find parts</button><Link href="/catalogue">Clear filters</Link></form><p>Page {filters.page+1} · {rows.length} entries</p>{rows.length?rows.map(item=><article className="catalogue-entry" key={item.id}>{cataloguePhotosReady()&&item.photo_id?<figure><img src={`/api/catalogue/photos/${item.id}`} alt={item.photo_alt} width={240}/></figure>:item.image_asset&&validCatalogueAsset(item.image_asset)&&<figure><img src={item.image_asset} alt="Parts sourcing illustration" width={240}/><figcaption>Illustration only — not a product photo.</figcaption></figure>}<h2><Link href={`/catalogue/${item.id}`}>{item.title}</Link></h2><p>{item.description}</p><p>{item.category} / {item.brand||'Make unspecified'} / {item.part_number||'Part number unspecified'}</p><Link href={`/request?part=${encodeURIComponent(`${item.title} ${item.part_number}`)}`}>Enquire about this part</Link></article>):<p>No published entries match these filters.</p>}<nav className="catalogue-pages" aria-label="Catalogue pages">{filters.page>0&&<Link href={pageHref(filters.page-1)}>Previous page</Link>} {hasMore&&<Link href={pageHref(filters.page+1)}>Next page</Link>}</nav></section></main>;
}
